import { inter } from '@/lib/fonts';

import { RightSidebar } from '@/app/right-sidebar';
import './globals.css';
import { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import { QueryProvider } from '@/components/provider/query-provider';
import { Suspense } from 'react';
import { Avatar } from '@/components/ui/avatar';
import { Skeleton } from '@/components/ui/skeleton';
import { SidebarToggler } from './sidebar-toggler';
import { SidebarProvider } from '@/components/provider/sidebar-provider';
import { LeftSidebar } from './left-sidebar';

import 'react-medium-image-zoom/dist/styles.css';

export const metadata: Metadata = {
  title: 'Skyblue',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'overscroll-none')}>
        <QueryProvider>
          <div className='max-w-[76rem] mx-auto flex'>
            <Suspense
              fallback={
                <>
                  <Avatar className='h-14 w-14'>
                    <Skeleton className='w-14 h-14 flex items-center justify-center' />
                  </Avatar>

                  <nav className='flex flex-col gap-1'>
                    {Array.from({ length: 3 })
                      .fill(0)
                      .map((_, index) => (
                        <Skeleton className='h-10 w-full' key={index} />
                      ))}
                  </nav>
                </>
              }
            >
              <SidebarProvider>
                <LeftSidebar />
                <SidebarToggler />
              </SidebarProvider>
            </Suspense>
            <main className='flex-1 border-x border-gray-200'>{children}</main>
            <RightSidebar />
          </div>

          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
